export type Schedule = {
	_id: string,
	date: number,
	orgId: string,
	studentId?: string,
	classId?: string,
	presentIds?: string[],
	courseId: string,
	teacherId: string,
	gradients: string[],
	startTime: number,
	endTime: number,
	remind?: boolean,
	courseContent?: string,
	previewContent?: string,
	feedback?: string,
	assignment?: string,
	consume: number,
	status: number,
	modifyDate?:number,
	operatorId?:string
}